# Generated by Django 4.1.7 on 2023-03-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('pages', '0002_pages_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='tasks',
            field=models.ManyToManyField(related_name='pages', to='tasks.tasks'),
        ),
    ]
