# Generated by Django 4.1.7 on 2023-03-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pages_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='tasks',
        ),
    ]
