# Generated by Django 4.1.7 on 2023-03-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_block_data_pageblocks_block_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='name',
            new_name='title',
        ),
    ]
