# Generated by Django 4.1.7 on 2023-03-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_name_pages_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageblocks',
            name='block_id',
        ),
        migrations.AddField(
            model_name='pageblocks',
            name='block_nextId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pageblocks',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
