# Generated by Django 4.1.7 on 2023-03-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_pageblocks_block_nextid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageblocks',
            name='block_nextId',
        ),
    ]
