# Generated by Django 4.1.7 on 2023-03-20 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_pageblocks_block_nextid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblocks',
            name='block_nextId',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
