# Generated by Django 4.1.7 on 2023-03-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_pages_tasks'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='page',
            field=models.ManyToManyField(related_name='tasks', to='pages.pages'),
        ),
    ]
