# Generated by Django 4.1.7 on 2023-03-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='page',
        ),
        migrations.AddField(
            model_name='tasks',
            name='due',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(default='Low', max_length=100),
        ),
    ]
