# Generated by Django 4.1.7 on 2023-03-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_title_tasks_name_remove_tasks_page_tasks_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(max_length=100),
        ),
    ]
