# Generated by Django 4.1.2 on 2022-10-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
