# Generated by Django 4.1.2 on 2022-10-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_delete_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='username',
            new_name='user',
        ),
    ]
